/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import Dominio.Usuario;
import Repository.Repositorio_Usuario_Db;
import java.util.List;

/**
 *
 * @author SEBASTIAN
 */
public class Ingreso_Usuario extends javax.swing.JFrame {
    Repositorio_Usuario_Db usuarios = new Repositorio_Usuario_Db();

    /**
     * Creates new form Ingreso_Usuario
     */
    public Ingreso_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid_usuario = new javax.swing.JTextField();
        bneliminar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        bnconsultar = new javax.swing.JButton();
        bnmodificar = new javax.swing.JButton();
        bningresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 83, -1, -1));
        getContentPane().add(txtid_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 80, 64, -1));

        bneliminar.setText("Eliminar");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 196, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 111, 142, -1));

        bnconsultar.setText(".....");
        bnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 65, -1, -1));

        bnmodificar.setText("Modificar");
        bnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 196, -1, -1));

        bningresar.setText("Ingresar");
        bningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bningresarActionPerformed(evt);
            }
        });
        getContentPane().add(bningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 199, -1, 20));

        jLabel2.setText("Ingresar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 20, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 117, -1, -1));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 145, -1, -1));
        getContentPane().add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 142, 142, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bningresarActionPerformed
        Usuario usuario= new Usuario();
        usuario.setNombre(txtnombre.getText());
        usuario.setContraseña(txtcontraseña.getText());
        usuarios.ingresar(usuario); 
        limpiar();
    }//GEN-LAST:event_bningresarActionPerformed

    private void bnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmodificarActionPerformed
        Usuario usua= new Usuario();
        usua.setId_usuario(Integer.parseInt(txtid_usuario.getText()));
        usua.setNombre(txtnombre.getText());
        usua.setContraseña(txtcontraseña.getText());
        usuarios.modificar(usua); 
        limpiar();
    }//GEN-LAST:event_bnmodificarActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        Usuario usua= new Usuario();
        usua.setId_usuario(Integer.parseInt(txtid_usuario.getText()));
        usuarios.eliminar(usua); 
        limpiar();
    }//GEN-LAST:event_bneliminarActionPerformed

    private void bnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultarActionPerformed
        Usuario usua= new Usuario();
        usua.setId_usuario(Integer.parseInt(txtid_usuario.getText()) );
        
        List<Usuario> usuario=usuarios.ConsultarId(usua);
        for(Usuario temp:usuario){
            txtnombre.setText(temp.getNombre());
            txtcontraseña.setText(temp.getContraseña());
        } 
        
    }//GEN-LAST:event_bnconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Usuario().setVisible(true);
            }
        });
    }
    
    public void limpiar(){
    txtid_usuario.setText("");
    txtnombre.setText("");
    txtcontraseña.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnconsultar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bningresar;
    private javax.swing.JButton bnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtid_usuario;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
